name: Run example script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          R -e "install.packages(c('mgcv','dismo','gbm','ggplot2','scales'), repos='https://cloud.r-project.org')"
      - name: Run example script
        run: |
          Rscript -e "source('R/calculate_methane_flux.R'); source('inst/examples/run_example.R')"
